### ISSUE TITLE
Question about Import.

### ISSUE THREAD

**Issue by ghost** [Yanndroid/Sudoku#2]
can you tell me how to import the sudoku in the game i mean what type of file and how i can store that file in my phone to import in application

**Comment by Yanndroid** [comment]
When you share a game via ⋮ > Share, you can select a file explorer to store it locally and then import it again by picking the file in the dialog.
Another way to import a game is when someone shares it with you (via WhatsApp for example) and you select the Sudoku app in the "Open with" dialog after clicking on the file or message.

**Comment by ghost** [comment]
> When you share a game via ⋮ > Share, you can select a file explorer to store it locally and then import it again by picking the file in the dialog. Another way to import a game is when someone shares it with you (via WhatsApp for example) and you select the Sudoku app in the "Open with" dialog after clicking on the file or message.

That's Something new to Know. Thank you!
