### ISSUE TITLE
sudoku algorithm 

### ISSUE THREAD

**Issue by ghost** [Yanndroid/Sudoku#3]
Which methods do you use for both the sudoku 4x4 and 9x9 algorithm and for the solver algorithm.?

**Comment by Yanndroid** [comment]
The "algorithms" are in `de.dlyt.yanndroid.sudoku.game.Game.java` (`makeGameFromEdit()` and `generateFields()`).
It's a recursive method to solve the sudoku by looping through all the fields and basically brute-forcing the solution.
Same goes for the generation, it puts random numbers in random fields, creates all the possible solutions for it, picks a random solution and then one by one removes a random number and checks if there's just one solution left.
I know this is probably the worst way to do this (and also the reason why 16x16 is impossible) but it initially only was a school project to solve sudokus.

**Comment by ghost** [comment]
Thank you for your reply. I'm learning how sudoku work that's why I need to
know that.

**Comment by Yanndroid** [comment]
Sure np. I might use a [library](https://github.com/sfuhrm/sudoku) in the future that does that much faster but I haven't checked it out yet. Maybe it can also help you.

**Comment by ghost** [comment]
That would be great, thanks!
